spring:
    datasource:
        url: jdbc:h2:mem:c48727c4-ba63-463f-8521-fe23b66eee0b
        username: sa
        password: 
        platform: h2
        hikari:
            connection-test-query: SELECT 1
            
    jpa:
        database: H2
        show-sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: validate
            
    flyway:
        baseline-on-migrate: true
        validate-on-migrate: true
