spring:
    datasource:
        url: jdbc:h2:mem:c48727c4-ba63-463f-8521-fe23b66eee0b
        username: sa
        password: 
        platform: h2
        hikari:
            connection-test-query: SELECT 1

logging:
    level.: DEBUG
